### ISSUE TITLE
Question about the implementation on MoKGE baseline

### ISSUE THREAD

**Issue by AvataGarde** [liuchenzhengyi/DimonGen#2]
Hi, I have some questions about your implementation on MoKGE part.
1. I noticed your implementation on GCN layer in utils/gnn.py are slightly different from the code in the MoKGE project (https://github.com/DM2-ND/MoKGE/blob/master/sources/kgmoe/graph_layer.py). Would the difference affect the performance?

2. Could you explain why the nodes are encoded twice by the tokenizer?
https://github.com/liuchenzhengyi/DimonGen/blob/01a823e8a15c641f60a51aa85387d4094bc19e04/trainer/__init__.py#L112
https://github.com/liuchenzhengyi/DimonGen/blob/01a823e8a15c641f60a51aa85387d4094bc19e04/trainer/__init__.py#L120

Thank you.

**Comment by liuchenzhengyi** [comment]
1. Could you please specify which part of code are you referring to? Basically, difference GNN layers should have a similar performance.
2. It is a typo caused by code merge. I will fix it. Thanks for poiniting out.
